<footer>
    <ul class="footer-nav">
        <li><a href="index.php">Home</a></li>
        <li><a href="about.php">About</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>
        <li><a href="manage.php">Manage</a></li>
    </ul>
<div class="contact">
<p>Contact us:</p>
<a href="mailto:104309099@student.swin.edu.au"><img src="images/mail.png" alt="mail" width="50" height="50"></a>
 <a href="https://www.facebook.com"><img src="images/fb.png" alt="fb" width="50" height="50"></a>
   <a href="https://www.instagram.com"><img src="images/ins.png" alt="ins" width="50" height="50"></a>
     <a href="https://www.twitter.com"><img src="images/twitter.png"  alt="tw" width="50" height="50"></a>
     <a href="https://www.linkedin.com"><img src="images/linkedln.png" alt="lin" width="50" height="50"></a>
</div><hr>
    <p class="credits">Graphics on this website made and designed by Adrien Krebet with the help of Minh Nguyen, Shane Lin, and Mirza Hizqeel Ahmad @Airnet Gateways 2023</p>
</footer>
