<nav class="navbar">
    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="about.php">About</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>
        <li><a href="manage.php">Manage</a></li>
        <li><a href="phpenhancements.php">Enhancements 2</a></li>
    </ul>
</nav>